const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Behaviors.Flash,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.AnimationFrameTag,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Arr.Acts.Pop,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{golge: 0},
	{arkaplan: 0},
	{spbeyaz: 0},
	{mebLogo: 0},
	{emegigecenler: 0},
	{about: 0},
	{reference: 0},
	{Logo: 0},
	{Sine: 0},
	{tebrikler: 0},
	{Touch: 0},
	{Mouse: 0},
	{Browser: 0},
	{Audio: 0},
	{AJAX: 0},
	{cumleler: 0},
	{cumlesirasi: 0},
	{btn_basla: 0},
	{btn_anasayfa: 0},
	{btn_emegigecenler: 0},
	{btn_kaynakca: 0},
	{btn_replay: 0},
	{durum: 0},
	{btn_ses: 0},
	{btn_tamekran: 0},
	{btn_Bilgi: 0},
	{btn_next: 0},
	{Timer: 0},
	{Sure: 0},
	{cumleCvp: 0},
	{soruCumle: 0},
	{cevap: 0},
	{bitisSure: 0},
	{cvpButon: 0},
	{Flash: 0},
	{donut: 0},
	{ButonAilesi: 0},
	{AnaSayfaGorseller: 0},
	{tiklanabilir: 0},
	{sure: 0},
	{secilenCumle: 0},
	{musicDurum: 0}
];

self.InstanceType = {
	golge: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	spbeyaz: class extends self.ISpriteInstance {},
	mebLogo: class extends self.ISpriteInstance {},
	emegigecenler: class extends self.ISpriteInstance {},
	about: class extends self.ISpriteInstance {},
	reference: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	tebrikler: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	cumleler: class extends self.IArrayInstance {},
	cumlesirasi: class extends self.IArrayInstance {},
	btn_basla: class extends self.ISpriteInstance {},
	btn_anasayfa: class extends self.ISpriteInstance {},
	btn_emegigecenler: class extends self.ISpriteInstance {},
	btn_kaynakca: class extends self.ISpriteInstance {},
	btn_replay: class extends self.ISpriteInstance {},
	btn_ses: class extends self.ISpriteInstance {},
	btn_tamekran: class extends self.ISpriteInstance {},
	btn_Bilgi: class extends self.ISpriteInstance {},
	btn_next: class extends self.ISpriteInstance {},
	Sure: class extends self.ITextInstance {},
	soruCumle: class extends self.ITextInstance {},
	cevap: class extends self.ITextInstance {},
	bitisSure: class extends self.ITextInstance {},
	cvpButon: class extends self.ISpriteInstance {},
	donut: class extends self.ISpriteInstance {},
	ButonAilesi: class extends self.ISpriteInstance {},
	AnaSayfaGorseller: class extends self.ISpriteInstance {}
}